platform :ios, '10.3'

target 'Transitions' do
    use_frameworks!
    
    pod "SimpleLogger", :git => "https://github.com/thinkaboutiter/SimpleLogger.git", :tag => "1.1.3"
    pod 'SnapKit', '~> 4.0'
end



